services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Copy sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./sql/servers.json:/pgadmin4/servers.json
    restart: always

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - APP_NAME=FlaskApp
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_CONNECTION=POSTGRES
      - WAIT_HOSTS=postgres:5432
    expose:
      - 8080
    depends_on:
      - postgres

  nginx:
    build: ./frontend
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
  postgres-data: